Repository sleppy-navigators/study-up-frontend, pull requests merged in 2025-06, with the labels that each got.

#44 Storybook/MSW/Reactotron 통합 및 그룹 채팅 뷰 기능 추가
  .storybook/preview.tsx
  ReactotronConfig.js
  app.config.js
  app/_layout.tsx
  bun.lockb
  domains/base/providers/reactotron-provider.tsx
  domains/chat/components/chat-view.tsx
  domains/chat/stories/chat-view.stories.tsx
  lib/react-query.tsx
  metro.config.js
  mocks/mocking-provider.tsx
Labels: size/L

#46 Storybook 및 MSW 코드가 비활성화 시 import되지 않도록 개선
  documents/pull-requests/2025-06-06-fix-avoid-storybook-top-level-import.md
  domains/base/providers/storybook-provider.tsx
Labels: size/M

#48 unstable_enablePackageExports로 인한 ESM import.meta.env 문제 수정
  documents/pull-requests/fix-zustand-esm-env-pr.md
  metro.config.js
Labels: size/S

#49 unstable_enablePackageExports로 인한 ESM import.meta.env 문제 수정
  documents/pull-requests/fix-zustand-esm-env-pr.md
  metro.config.js
Labels: size/S

#51 EAS 빌드 프로필별 환경 변수 관리 개선
  documents/pull-requests/infra-env-variables-in-eas-pr.md
  eas.json
Labels: size/M

#45 feat: 챌린지 보증금 입력폼 추가
  domains/challenge/api/types.ts
  domains/challenge/pages/create-challenge.tsx
  domains/challenge/types.ts
Labels: size/M
